[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=23.3.0",
    "ruff>=0.0.265",
]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "dwpeng", email = "1732889554@qq.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}
